name: specta_paas
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  docker_commander: ^2.0.15
  docker_process: ^1.3.1
  galaxeus_lib: ^0.0.14